id: IB4611B05
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:08:28+00:00'
last_modified: '2022-06-08T14:18:26.978650+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC273
  title: སྤྲིན་དཀར་གྱི་འདབ་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E377:
      image_group_id: I2PD20337
      title: ''
      total_pages: 346
      order: 1
      base_file: E377.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
